#!/bin/sh
#
# bootstrap script to get the tools needed to build the specs within a UNIX shell

export LC_ALL=
FOUND=
NEEDED=

BOOTSTRAP_MAKE=bootstrap.mak
RUNTIMES_MAKE=runtimes.mak

check_version() {
    gotver=$2
    gotmajor=`echo $gotver|cut -d. -f1`
    gotminor=`echo $gotver|cut -d. -f2`
    gotmicro=`echo $gotver|cut -d. -f3`
    [ -z "$gotmicro" ] && gotmicro=0
    needmajor=`echo $3|cut -d. -f1`
    needminor=`echo $3|cut -d. -f2`
    needmicro=`echo $3|cut -d. -f3`
    [ -z "$needmicro" ] && needmicro=0
    if [ "$needmajor" -ne "$gotmajor" \
         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -gt "$gotminor" \
         -o "$needmajor" -eq "$gotmajor" -a "$needminor" -eq "$gotminor" -a "$needmicro" -gt "$gotmicro" ]
    then
        echo "$1 too old (got $gotver, needed $3)"
        NEEDED="$NEEDED $1"
    else
        FOUND="$FOUND $1"
        echo "found $1 version $2 (needed $3)"
    fi
}

check() {
    if ! $1 --version >/dev/null 2>&1 && ! $1 -version >/dev/null 2>&1
    then
        echo "$1 not found"
        NEEDED="$NEEDED $1"
    else
        # found, need to check version ?
        if [ -z "$2" ];then
            FOUND="$FOUND $1"
            echo "found $1"
        else
            gotver=`$1 --version | head -1 | sed s/'.* '//`
            check_version $1 $gotver $2
        fi
    fi
}

# check make
check mmark 2.1.1
check xml2rfc 2.30.0

cat > $BOOTSTRAP_MAKE << EOF
PREFIX=\$(abspath ./build)
EOF

echo "# calls the local or installed tool " > $RUNTIMES_MAKE

for t in $FOUND; do
    echo ".$t:" >> $BOOTSTRAP_MAKE
    echo "$t" | awk '{ tool = sprintf("%s_CALL := %s", toupper($0), $0); print tool }' >> $RUNTIMES_MAKE
done

for t in $NEEDED; do
    echo .$t: .build$t >> $BOOTSTRAP_MAKE
    PACKAGES="$PACKAGES $t"
    TARGETS="$TARGETS .build$t"
    echo "$t" | awk '{ tool = sprintf("%s_CALL := ./%s", toupper($0), $0); print tool }' >> $RUNTIMES_MAKE
done

[ -n "$PACKAGES" ] && echo "To-be-built packages: $PACKAGES"

case `uname` in
	Linux)
		MMARK_OS=linux
	;;
	Darwin)
		MMARK_OS=darwin
	;;
	MINGW32*|MINGW64*|*MSYS*)
		MMARK_OS=windows
	;;
	*)
		echo Unsupported build OS `uname`
		exit 1
	;;
esac
case `uname -m` in
	x86_64)
		MMARK_MACHINE=amd64
	;;
	arm64)
		MMARK_MACHINE=arm64
	;;
	arm)
		MMARK_MACHINE=arm
	;;
	*)
		echo Unsupported build CPU `uname -m`
		exit 1
	;;
esac

cat >> $BOOTSTRAP_MAKE << EOF
all: $TARGETS
	@echo "You are ready to build Matroska specifications"

MMARK_VERSION=2.1.1
MMARK_OS=$MMARK_OS
MMARK_MACHINE=$MMARK_MACHINE

include tools.mak
EOF

make -f $BOOTSTRAP_MAKE